### ISSUE TITLE
上应用需要官方同意么

### ISSUE THREAD

**Issue by ghost** [cssmagic/Awesome-Nebulas#26]
我是小白，就是想问一下上一个DAPP需要公链官方认可么？比如博.彩、色.情的DAPP应用（打个比方，因为这两个最挣钱）。

因为不同地区法律不一致，会不会因为主链在中国大陆而不能上此类应用，如果公链不能自主上应用，还是公开的公链么！

**Comment by cssmagic** [comment]
可以把公链理解为分布式数据库或云存储。理论上，链不会对数据作审查。

星云链的官方节点目前不在中国大陆。

作为提供 Web 服务的经营者（比如 DApp 的开发者和运营者），需要遵守所在地的法律法规。
